### ISSUE TITLE
Support for L5.5

### ISSUE THREAD

**Issue by serneelsalexis** [spatie/laravel-blade-javascript#21]
Hi,

Thanks for the great package.

I see the `dev-laravel-55` branch. But it still relies on a `contracts-dev`.
Would it possible to merge the support on the `master`branch?

I unfortunately can't PR those types of changes with my knowledge.

Thanks,

**Comment by freekmurze** [comment]
Soon.

**Comment by lewebdalex** [comment]
Thanks for the quick fix!
Have a nice day.
