### ISSUE TITLE
Conflicts with Vue.js?

### ISSUE THREAD

**Issue by gmask** [spatie/laravel-blade-javascript#23]
Whenever I use the `@javascript` tag in my blade templates I get the following Vue.js error:

```
- Templates should only be responsible for mapping the state to the UI. Avoid placing tags with side-effects in your templates, such as <script>, as they will not be parsed.
```

Removing the tags from the template fixes the issue. Should I be using Vuex instead of this package? I very much prefer the simplicity of this package.

**Comment by freekmurze** [comment]
Avoid placing the `@javascript` directive inside an element where Vue components are mounted.
