### ISSUE TITLE
no CSP Support

### ISSUE THREAD

**Issue by Gummibeer** [spatie/laravel-blade-javascript#34]
At the moment there is no CSP support by default - which is a bit strange cause you guys have also a laravel csp package.
> Refused to execute inline script because it violates the following Content Security Policy directive: "script-src ...". Either the 'unsafe-inline' keyword, a hash ('...'), or a nonce ('nonce-...') is required to enable inline execution.

I don't want to allow inline scripts - so I have to set something on the script tag itself. Atm I've overriden the `\Spatie\BladeJavaScript\Renderer` class but this isn't optimal - there would be several ways to fix this.

**laravel-csp package related**
1) add the hash of the inline script to the policy https://github.com/spatie/laravel-csp/issues/33
2) use the `csp_nonce()` function on the script

**general**
3) use a blade file for the script tag that could be overriden

which one do you like the most?

**Comment by freekmurze** [comment]
I don't understand the need of doing a fix in this package?

Couldn't you just use the csp package in your project to solve this problem?

**Comment by Gummibeer** [comment]
For everything I create by my own I can. And atm I'm also overriding the renderer class of this package to add the nonce to the script tag.
I don't request to require the CSP package but support it - made it easy to adjust the generated HTML.

To give the most flexibility I like the blade template idea the most.

**Comment by freekmurze** [comment]
I still don't 100% grasp what you're trying to accomplish. But do send a PR with how you like things to be set up and we'll take it from there.
