### ISSUE TITLE
syntax error, unexpected '<'

### ISSUE THREAD

**Issue by bradley-varol** [spatie/laravel-blade-javascript#37]
I'm using this package like so
`@javascript('url', {{ route('url') }})`
and receiving
`syntax error, unexpected '<' (View: [redacted])`

**Comment by freekmurze** [comment]
The tests seem to be indicated that everything is working properly. Are you using the latest version of Laravel? If possible, please PR a failing test for us to look at.

**Comment by bradley-varol** [comment]
I'll try this package again on another project in the near future and get back to you if I have issues.
