### ISSUE TITLE
Append values to the existing namespace instead of override.

### ISSUE THREAD

**Issue by nesskyy** [spatie/laravel-blade-javascript#38]
Hi! In some situations, to keep consistency, there is a need to use the same window namespace for custom solutions as we might use for assigning data via `@javascript()`. Current implementation of the module overrides data that have been declared before `@javascript()`. What do you think about appending data to the namespace if such already exists (and maybe even make it configurable?) instead of just clearing that?

**Comment by freekmurze** [comment]
I'd like to keep this package very simple. Currently it supports only our usecases. If you need extra funtionality, feel freek to fork our code.
