### ISSUE TITLE
Can't use function as value

### ISSUE THREAD

**Issue by danielboendergaard** [spatie/laravel-blade-javascript#4]
When using a function as the value e.g. `@javascript('date', date('Y-m-d'))` the last parenthesis will get removed by this function and results in a syntax error:
https://github.com/spatie/laravel-blade-javascript/blob/master/src/BladeJavaScriptServiceProvider.php#L29

When using the array syntax, it works as expected: `@javascript(['date' => date('Y-m-d')])`

**Comment by freekmurze** [comment]
Thanks for reporting this. I've fixed it in the newly tagged version `1.0.3`.
