### ISSUE TITLE
Library generating invalid HTML output

### ISSUE THREAD

**Issue by mallardduck** [spatie/laravel-blade-javascript#42]
Just started using this library and I noticed that the scripts are being added in an invalid manner. That's to say, when using this library the HTML output from Laravel now contains invalid HTML markup.

For illustration purpose I've created a simple/empty template file. You can see this here:

```
<script>window['key'] = 'value';</script>
<!DOCTYPE html>
<html lang="en">
<head>
<title>Test</title>
</head>
</html>
```

When you attempt to validate this with an HTML validator it throws some errors. In total this creates 4 errors in the W3 HTML validator.

- Start tag seen without seeing a doctype first. Expected <!DOCTYPE html>.
- Stray doctype.
- Stray start tag html.
- Cannot recover after last error. Any further errors will be ignored.

**Comment by mallardduck** [comment]
I wonder if it would be possible to 'resolve' this by creating a Blade directive that prints all the output. 

To make this backward compatible maybe it would require adding a setting/flag too. This way it will do the current behavior as default. However once the new setting is turned on, then it would no longer output unless the new directive is included.

**Comment by sebastiandedeyne** [comment]
This isn't really a package issue. The script gets rendered wherever you place it in your Blade view, it looks like you rendered the script before your HTML here.

**Comment by mallardduck** [comment]
Oh duh! So simple, but I didn't even think about that.

I assumed these were to be used similar to some of the builtin blade directives. Like push for instance where you don't necessarily put it inline - just somewhere in the view. Sorry for the dumb question/issue report!

Moved things around as you suggested and it's all good now. Thanks!
