### ISSUE TITLE
Cannot install laravel-javascript-views package https://packagist.org/packages/spatie/laravel-javascript-views

### ISSUE THREAD

**Issue by ahmedwaleedlango** [spatie/laravel-blade-javascript#43]
I know this is not the right place to open this issue but I cannot find a laravel javascript view package on Github, Is it still open source?

**Comment by sebastiandedeyne** [comment]
laravel-javascript-views was an experiment, and has been removed. I recommend checking out [Inertia.js](https://github.com/inertiajs/inertia) instead.
