### ISSUE TITLE
About the minimal php version

### ISSUE THREAD

**Issue by shadoWalker89** [spatie/laravel-blade-javascript#5]
Hi,

Most of your packages require php 7 and honestly this package doesn't need php 7.
It is a simple package that 80% of the php users including me still use php 5

Why deny us such a great package for the sake of type hinting the return values ?
It would be nice if you could use php 5 instead.

**Comment by freekmurze** [comment]
Hi,

this package not only uses type hinting, but the tests use anonymous classes as well. This makes testing the functionality a whole lot easier.

In [this blogpost](https://murze.be/2016/01/why-we-are-requiring-php-7-for-our-new-packages/) I explained why we are mostly creating PHP 7 packages. Tldr: we don't use PHP 5 ourselves anymore and for our business there's no value in maintaining compatibility with PHP 5.

You are free to fork this package and modify it so it can be used with PHP 5.X. Or you can take a look at this one: https://github.com/laracasts/PHP-Vars-To-Js-Transformer
