### ISSUE TITLE
Fail to pass floats

### ISSUE THREAD

**Issue by FMate** [spatie/laravel-blade-javascript#7]
When I try to pass float variable, lbj turns it to integer with out fractional part. For example:

@javascript([
    ... ,
    'float' => 4.5
])

console.log(float) ==> 4

How can I pass float variable to js?

**Comment by sebastiandedeyne** [comment]
There was a little bug that casted floats to ints before they got rendered. Just tagged v1.0.5 that should resolve the issue!
